[phases.setup]
nixPkgs = ["php83", "php83Extensions.curl", "php83Extensions.dom", "php83Extensions.fileinfo", "php83.extensions.gd", "php83.extensions.mbstring", "php83.extensions.mysqlnd", "php83.extensions.pdo_mysql", "php83.extensions.tokenizer", "php83.extensions.xml", "php83.extensions.bcmath"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT"
